const K='xenor_data_v2';
const D={
 services:[{id:1,i:'🎨',n:'تصميم السوشيال ميديا',d:'تصميم محتوى وهوية بصرية احترافية.',p:'حسب الباقة'},{id:2,i:'📣',n:'إعلانات ممولة',d:'إدارة وتجهيز الحملات الإعلانية.',p:'حسب الحملة'},{id:3,i:'🌐',n:'مواقع وتطبيقات',d:'مواقع شركات ومتاجر وتطبيقات موبايل.',p:'حسب المشروع'},{id:4,i:'🤖',n:'حلول AI',d:'أدوات وأفكار ذكاء اصطناعي للمحتوى والتسويق.',p:'حسب الطلب'}],
 orders:[],users:[{id:1,name:'XENOR Team',bio:'Digital creators & technology',avatar:'X',following:0}],posts:[{id:1,user:'XENOR Team',avatar:'X',text:'أهلًا بك في XENOR Social 🚀 شارك أفكارك، أعمالك، وفيديوهاتك مع المجتمع.',likes:12,comments:[{user:'Ahmed',text:'بداية قوية 🔥'}],shares:3,date:'الآن'}],stories:[],notifications:[],messages:[],social:{Facebook:'',Instagram:'',TikTok:'',LinkedIn:'',Pinterest:'',YouTube:'',WhatsApp:''}};
let data=JSON.parse(localStorage.getItem(K)||'null')||D;
const save=()=>localStorage.setItem(K,JSON.stringify(data));
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]));
const hash=()=>location.hash||'#home';
function layout(content){return `<div class="shell">${content}</div>`}
function render(){let h=hash();let content=h.startsWith('#admin')?admin():h.startsWith('#feed')?feed():h.startsWith('#reels')?reels():h.startsWith('#market')?market():h.startsWith('#academy')?academy():h.startsWith('#profile')?profile():home();document.getElementById('app').innerHTML=layout(content);document.getElementById('year').textContent=new Date().getFullYear();document.getElementById('social').innerHTML=Object.entries(data.social).filter(x=>x[1]).map(x=>`<a href="${esc(x[1])}" target="_blank" rel="noopener">${esc(x[0])}</a>`).join('')}
function nav(){return `<div class="mobileNav"><a href="#home">⌂<small>الرئيسية</small></a><a href="#feed">◉<small>المجتمع</small></a><a href="#reels">▶<small>Reels</small></a><a href="#profile">●<small>حسابي</small></a><a href="#admin">⚙<small>إدارة</small></a></div>`}
function home(){return `<section class="hero"><div><div class="yellow">DIGITAL + SOCIAL + AI</div><h1>XENOR <span class="yellow">SOCIAL HUB</span></h1><p class="muted">منصة واحدة للمحتوى، المجتمع، الخدمات الرقمية، السوق، والأكاديمية.</p><a class="btn primary" href="#feed">ادخل المجتمع</a> <a class="btn" href="#services">الخدمات</a></div><div class="heroCard"><b>X</b><h2>اصنع حضورك الرقمي</h2><p class="muted">انشر، تواصل، تعلّم، واطلب خدماتك.</p><span class="tag">Social</span> <span class="tag">AI</span> <span class="tag">Web</span></div></section><section id="services"><h2>خدمات XENOR</h2><div class="grid">${data.services.map(s=>`<div class="card"><div class="icon">${esc(s.i)}</div><h3>${esc(s.n)}</h3><p class="muted">${esc(s.d)}</p><span class="tag">${esc(s.p)}</span><br><a class="btn primary" href="#contact">اطلب الآن</a></div>`).join('')}</div></section><section><h2>كل شيء في مكان واحد</h2><div class="grid"><a class="card linkcard" href="#feed"><h3>📰 المجتمع</h3><p class="muted">منشورات وتعليقات ومتابعة.</p></a><a class="card linkcard" href="#reels"><h3>🎬 Reels</h3><p class="muted">فيديوهات قصيرة ومحتوى مرئي.</p></a><a class="card linkcard" href="#market"><h3>🛒 Market</h3><p class="muted">خدمات ومنتجات رقمية.</p></a><a class="card linkcard" href="#academy"><h3>📚 Academy</h3><p class="muted">تعلم التسويق والمحتوى والـAI.</p></a></div></section><section id="contact"><h2>اطلب خدمة</h2><form class="form" onsubmit="order(event)"><input name="name" required placeholder="الاسم"><input name="phone" required placeholder="رقم الهاتف / واتساب"><input name="email" type="email" placeholder="البريد الإلكتروني"><select name="service" required><option value="">اختر الخدمة</option>${data.services.map(s=>`<option value="${s.id}">${esc(s.n)}</option>`).join('')}</select><textarea name="message" placeholder="تفاصيل الطلب"></textarea><button class="btn primary">إرسال الطلب</button></form></section>${nav()}`}
function feed(){return `<section><div class="sectionHead"><div><h2>📰 XENOR Community</h2><p class="muted">منشورات المجتمع</p></div><button class="btn primary" onclick="focusPost()">+ منشور</button></div><div class="composer" id="composer"><textarea id="postText" placeholder="بماذا تفكر؟ شارك منشورًا مع مجتمع XENOR..."></textarea><div><input id="postMedia" placeholder="رابط صورة/فيديو (اختياري)"><button class="btn primary" onclick="createPost()">نشر</button></div></div><div class="stories"><div class="story add" onclick="addStory()">＋<span>إضافة Story</span></div>${data.stories.map(s=>`<div class="story"><b>${esc(s.avatar)}</b><span>${esc(s.text)}</span></div>`).join('')}</div>${data.posts.map(postCard).join('')}</section>${nav()}`}
function postCard(p){return `<article class="post"><div class="postTop"><div class="avatar">${esc(p.avatar||'X')}</div><div><b>${esc(p.user)}</b><small class="muted"> · ${esc(p.date||'الآن')}</small></div></div><p>${esc(p.text)}</p>${p.media?`<div class="media"><img src="${esc(p.media)}" onerror="this.style.display='none'" alt="media"></div>`:''}<div class="postActions"><button onclick="likePost(${p.id})">❤️ ${p.likes||0}</button><button onclick="commentPost(${p.id})">💬 ${p.comments?.length||0}</button><button onclick="sharePost(${p.id})">↗️ ${p.shares||0}</button><button onclick="reportPost(${p.id})">⚑</button></div>${(p.comments||[]).slice(-3).map(c=>`<div class="comment"><b>${esc(c.user)}:</b> ${esc(c.text)}</div>`).join('')}</article>`}
function reels(){let rs=data.posts.filter(p=>p.media);return `<section><h2>🎬 XENOR Reels</h2><div class="reels">${(rs.length?rs:data.posts).map(p=>`<article class="reel"><div class="reelBox">${p.media?`<img src="${esc(p.media)}" alt="reel">`:'XENOR'}</div><h3>${esc(p.user)}</h3><p>${esc(p.text)}</p><button class="btn" onclick="likePost(${p.id})">❤️ ${p.likes||0}</button></article>`).join('')}</div></section>${nav()}`}
function market(){return `<section><h2>🛒 XENOR Market</h2><p class="muted">خدمات رقمية قابلة للطلب.</p><div class="grid">${data.services.map(s=>`<div class="card"><h3>${esc(s.n)}</h3><p class="muted">${esc(s.d)}</p><span class="tag">${esc(s.p)}</span><a class="btn primary" href="#contact">اطلب</a></div>`).join('')}</div></section>${nav()}`}
function academy(){return `<section><h2>📚 XENOR Academy</h2><div class="grid"><div class="card"><h3>أساسيات التسويق</h3><p class="muted">محتوى تدريبي عملي.</p></div><div class="card"><h3>صناعة المحتوى</h3><p class="muted">أفكار وقوالب للمحتوى.</p></div><div class="card"><h3>AI في العمل</h3><p class="muted">استخدام أدوات الذكاء الاصطناعي.</p></div></div></section>${nav()}`}
function profile(){let u=data.users[0];return `<section><div class="profileHero"><div class="bigAvatar">${esc(u.avatar)}</div><h2>${esc(u.name)}</h2><p class="muted">${esc(u.bio)}</p><button class="btn primary" onclick="editProfile()">تعديل الملف</button></div><h2>منشوراتي</h2>${data.posts.filter(p=>p.user===u.name).map(postCard).join('')||'<p class="muted">لا توجد منشورات بعد.</p>'}</section>${nav()}`}
function admin(){if(sessionStorage.xenor!=='1')return `<section class="admin"><div class="panel"><h2>دخول الإدارة</h2><form class="form" onsubmit="login(event)"><input name="u" placeholder="اسم المستخدم" required><input name="p" type="password" placeholder="كلمة المرور" required><button class="btn primary">دخول</button></form><p class="muted">نسخة تجريبية محلية: admin / XENOR2026</p></div></section>`;return `<section class="admin"><h2>لوحة إدارة XENOR</h2><div class="stats"><div class="stat"><b>${data.services.length}</b>الخدمات</div><div class="stat"><b>${data.orders.length}</b>الطلبات</div><div class="stat"><b>${data.posts.length}</b>المنشورات</div><div class="stat"><b>${data.users.length}</b>المستخدمون</div></div><div class="panel"><h3>إضافة خدمة</h3><form class="form" onsubmit="add(event)"><input name="n" placeholder="اسم الخدمة" required><input name="i" placeholder="أيقونة"><input name="p" placeholder="السعر"><textarea name="d" placeholder="الوصف"></textarea><button class="btn primary">إضافة</button></form><h3>الخدمات</h3>${data.services.map(s=>`<div class="row"><span>${esc(s.i)} ${esc(s.n)}</span><button class="danger" onclick="del(${s.id})">حذف</button></div>`).join('')}<h3>الطلبات</h3>${data.orders.length?data.orders.map(o=>`<div class="card"><b>${esc(o.name)}</b> — ${esc(o.phone)}<br>${esc(o.message||'')}</div>`).join(''):'<p class="muted">لا توجد طلبات.</p>'}<h3>إدارة المنشورات</h3>${data.posts.map(p=>`<div class="row"><span>${esc(p.user)} — ${esc(p.text).slice(0,60)}</span><button class="danger" onclick="removePost(${p.id})">حذف</button></div>`).join('')}<h3>روابط السوشيال</h3><form class="form" onsubmit="social(event)">${Object.keys(data.social).map(k=>`<input name="${k}" value="${esc(data.social[k])}" placeholder="${k} URL">`).join('')}<button class="btn primary">حفظ الروابط</button></form><button class="btn" onclick="logout()">خروج</button></div></section>`}
function order(ev){ev.preventDefault();let o=Object.fromEntries(new FormData(ev.target));o.id=Date.now();o.date=new Date().toLocaleString('ar-EG');data.orders.unshift(o);save();ev.target.reset();alert('تم إرسال الطلب بنجاح')}
function createPost(){let t=document.getElementById('postText').value.trim();if(!t)return alert('اكتب المنشور أولًا');data.posts.unshift({id:Date.now(),user:data.users[0].name,avatar:data.users[0].avatar,text:t,media:document.getElementById('postMedia').value.trim(),likes:0,comments:[],shares:0,date:'الآن'});save();render()}
function likePost(id){let p=data.posts.find(x=>x.id===id);if(p){p.likes=(p.likes||0)+1;save();render()}}
function commentPost(id){let t=prompt('اكتب تعليقك');if(!t)return;let p=data.posts.find(x=>x.id===id);p.comments=p.comments||[];p.comments.push({user:data.users[0].name,text:t});save();render()}
function sharePost(id){let p=data.posts.find(x=>x.id===id);if(p){p.shares=(p.shares||0)+1;save();navigator.clipboard?.writeText(location.href);alert('تم تسجيل المشاركة ونسخ رابط الصفحة') ;render()}}
function reportPost(id){data.notifications.unshift({id:Date.now(),text:'بلاغ على منشور #'+id});save();alert('تم إرسال البلاغ للإدارة')}
function removePost(id){data.posts=data.posts.filter(p=>p.id!==id);save();render()}
function addStory(){let t=prompt('اكتب Story قصيرة');if(t){data.stories.unshift({id:Date.now(),avatar:data.users[0].avatar,text:t});save();render()}}
function focusPost(){location.hash='#feed';setTimeout(()=>document.getElementById('postText')?.focus(),50)}
function editProfile(){let n=prompt('اسم الحساب',data.users[0].name);if(n){data.users[0].name=n;save();render()}}
function login(ev){ev.preventDefault();let f=new FormData(ev.target);if(f.get('u')==='admin'&&f.get('p')==='XENOR2026'){sessionStorage.xenor='1';render()}else alert('بيانات الدخول غير صحيحة')}
function logout(){sessionStorage.removeItem('xenor');render()}
function add(ev){ev.preventDefault();let f=new FormData(ev.target);data.services.push({id:Date.now(),n:f.get('n'),i:f.get('i')||'✦',p:f.get('p')||'حسب الطلب',d:f.get('d')||''});save();render()}
function del(id){data.services=data.services.filter(s=>s.id!==id);save();render()}
function social(ev){ev.preventDefault();let f=new FormData(ev.target);Object.keys(data.social).forEach(k=>data.social[k]=f.get(k)||'');save();render();alert('تم حفظ الروابط')}
addEventListener('hashchange',render);render();

function goBack(){if(history.length>1){history.back()}else{location.hash='#home'}}
