const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json;charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'content-type,authorization','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS'}});
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha(s){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))}
async function token(){return btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'')}
async function auth(req,env){const h=req.headers.get('authorization')||'';if(!h.startsWith('Bearer '))return null;const th=await sha(h.slice(7));const r=await env.DB.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(th,new Date().toISOString()).first();return r||null}
async function notify(env,userId,type,actorId,text,entityId=null){await env.DB.prepare('INSERT INTO notifications(user_id,type,actor_id,entity_id,text) VALUES(?,?,?,?,?)').bind(userId,type,actorId,entityId,text).run()}
async function main(req,env){if(req.method==='OPTIONS')return json({ok:true});const u=new URL(req.url),p=u.pathname,m=req.method;
 if(p==='/api/health')return json({ok:true,service:'XENOR Social API',time:new Date().toISOString()});
 if(p==='/api/auth/register'&&m==='POST'){const b=await req.json();if(!b.name||!b.email||!b.password||b.password.length<8)return json({error:'بيانات التسجيل غير مكتملة'},400);const exists=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(b.email.toLowerCase()).first();if(exists)return json({error:'البريد مستخدم بالفعل'},409);const ph=await sha(b.password);const r=await env.DB.prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?) RETURNING id,name,email,role').bind(b.name,b.email.toLowerCase(),ph).first();const t=await token();await env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(await sha(t),r.id,new Date(Date.now()+30*864e5).toISOString()).run();return json({user:r,token:t},201)}
 if(p==='/api/auth/login'&&m==='POST'){const b=await req.json();const r=await env.DB.prepare('SELECT id,name,email,password_hash,role FROM users WHERE email=?').bind((b.email||'').toLowerCase()).first();if(!r||r.password_hash!==await sha(b.password||''))return json({error:'بيانات الدخول غير صحيحة'},401);const t=await token();await env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(await sha(t),r.id,new Date(Date.now()+30*864e5).toISOString()).run();delete r.password_hash;return json({user:r,token:t})}
 const me=await auth(req,env); if(!me)return json({error:'يجب تسجيل الدخول'},401);
 if(p==='/api/me')return json({user:me});
 if(p==='/api/users'&&m==='GET'){const q=u.searchParams.get('q')||'';const rows=await env.DB.prepare('SELECT id,name,bio,avatar_url,created_at FROM users WHERE name LIKE ? OR email LIKE ? ORDER BY id DESC LIMIT 50').bind('%'+q+'%','%'+q+'%').all();return json({users:rows.results})}
 if(p==='/api/friends/request'&&m==='POST'){const b=await req.json();if(me.id===b.user_id)return json({error:'لا يمكن إرسال طلب لنفسك'},400);await env.DB.prepare('INSERT INTO friendships(requester_id,addressee_id,status) VALUES(?,?,?) ON CONFLICT(requester_id,addressee_id) DO UPDATE SET status="pending",updated_at=CURRENT_TIMESTAMP').bind(me.id,b.user_id).run();await notify(env,b.user_id,'friend_request',me.id,`${me.name} أرسل لك طلب صداقة`);return json({ok:true})}
 if(p==='/api/friends/respond'&&m==='POST'){const b=await req.json();const f=await env.DB.prepare('SELECT * FROM friendships WHERE id=? AND addressee_id=?').bind(b.friendship_id,me.id).first();if(!f)return json({error:'الطلب غير موجود'},404);if(!['accepted','rejected'].includes(b.status))return json({error:'حالة غير صالحة'},400);await env.DB.prepare('UPDATE friendships SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(b.status,f.id).run();if(b.status==='accepted')await notify(env,f.requester_id,'friend_accepted',me.id,`${me.name} قبل طلب الصداقة`,f.id);return json({ok:true,status:b.status})}
 if(p==='/api/friends'&&m==='GET'){const rows=await env.DB.prepare('SELECT f.*,u.id user_id,u.name,u.avatar_url FROM friendships f JOIN users u ON u.id=CASE WHEN f.requester_id=? THEN f.addressee_id ELSE f.requester_id END WHERE (f.requester_id=? OR f.addressee_id=?) ORDER BY f.updated_at DESC').bind(me.id,me.id,me.id).all();return json({friends:rows.results})}
 if(p==='/api/posts'&&m==='GET'){const rows=await env.DB.prepare('SELECT p.id,p.text,p.media_url,p.media_type,p.created_at,u.id user_id,u.name,u.avatar_url,(SELECT COUNT(*) FROM post_likes l WHERE l.post_id=p.id) likes,(SELECT COUNT(*) FROM comments c WHERE c.post_id=p.id) comments FROM posts p JOIN users u ON u.id=p.user_id ORDER BY p.id DESC LIMIT 100').all();return json({posts:rows.results})}
 if(p==='/api/posts'&&m==='POST'){const b=await req.json();if(!b.text&&!b.media_url)return json({error:'المنشور فارغ'},400);const r=await env.DB.prepare('INSERT INTO posts(user_id,text,media_url,media_type) VALUES(?,?,?,?) RETURNING id').bind(me.id,b.text||'',b.media_url||'',b.media_type||'').first();return json({id:r.id},201)}
 const like=p.match(/^\/api\/posts\/(\d+)\/like$/);if(like&&m==='POST'){const id=Number(like[1]);await env.DB.prepare('INSERT OR IGNORE INTO post_likes(post_id,user_id) VALUES(?,?)').bind(id,me.id).run();const post=await env.DB.prepare('SELECT user_id FROM posts WHERE id=?').bind(id).first();if(post&&post.user_id!==me.id)await notify(env,post.user_id,'like',me.id,`${me.name} أعجب بمنشورك`,id);return json({ok:true})}
 const comment=p.match(/^\/api\/posts\/(\d+)\/comments$/);if(comment&&m==='POST'){const b=await req.json();const id=Number(comment[1]);await env.DB.prepare('INSERT INTO comments(post_id,user_id,text) VALUES(?,?,?)').bind(id,me.id,b.text||'').run();const post=await env.DB.prepare('SELECT user_id FROM posts WHERE id=?').bind(id).first();if(post&&post.user_id!==me.id)await notify(env,post.user_id,'comment',me.id,`${me.name} علّق على منشورك`,id);return json({ok:true},201)}
 if(p==='/api/notifications'&&m==='GET'){const rows=await env.DB.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 100').bind(me.id).all();return json({notifications:rows.results})}
 if(p==='/api/messages'&&m==='GET'){const other=Number(u.searchParams.get('user_id'));const rows=await env.DB.prepare('SELECT id,sender_id,receiver_id,text,created_at,read_at FROM messages WHERE (sender_id=? AND receiver_id=?) OR (sender_id=? AND receiver_id=?) ORDER BY id ASC LIMIT 200').bind(me.id,other,other,me.id).all();return json({messages:rows.results})}
 if(p==='/api/messages'&&m==='POST'){const b=await req.json();await env.DB.prepare('INSERT INTO messages(sender_id,receiver_id,text) VALUES(?,?,?)').bind(me.id,b.user_id,b.text||'').run();await notify(env,b.user_id,'message',me.id,`رسالة جديدة من ${me.name}`);return json({ok:true},201)}
 if(p==='/api/reports'&&m==='POST'){const b=await req.json();await env.DB.prepare('INSERT INTO reports(reporter_id,post_id,reported_user_id,reason) VALUES(?,?,?,?)').bind(me.id,b.post_id||null,b.reported_user_id||null,b.reason||'بلاغ').run();return json({ok:true},201)}
 if(p==='/api/admin/reports'&&m==='GET'){if(me.role!=='admin')return json({error:'غير مصرح'},403);const rows=await env.DB.prepare('SELECT r.*,u.name reporter_name FROM reports r JOIN users u ON u.id=r.reporter_id ORDER BY r.id DESC LIMIT 200').all();return json({reports:rows.results})}
 if(p==='/api/admin/users'&&m==='GET'){if(me.role!=='admin')return json({error:'غير مصرح'},403);const rows=await env.DB.prepare('SELECT id,name,email,role,created_at FROM users ORDER BY id DESC LIMIT 500').all();return json({users:rows.results})}
 return json({error:'Not Found'},404)}
export default {async fetch(req,env){try{return await main(req,env)}catch(e){return json({error:e.message||'Server error'},500)}}};
